CREATE TABLE volunteers (
    vid SMALLINT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    occupation VARCHAR(255) NOT NULL,
    startDate VARCHAR(255) NOT NULL,
    endDate VARCHAR(255) NOT NULL,
    PRIMARY KEY (vid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE locations (
    lid SMALLINT NOT NULL AUTO_INCREMENT,
    country VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    need VARCHAR(255) NOT NULL,
    PRIMARY KEY (lid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;