SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS volunteers;
CREATE TABLE volunteers (
    vid SMALLINT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    occupation VARCHAR(255) NOT NULL,
    season VARCHAR(255) NOT NULL,
    days VARCHAR(255) NOT NULL, 
    region VARCHAR(255) NOT NULL,
    startDate VARCHAR(255) NOT NULL,
    endDate VARCHAR(255) NOT NULL,
    PRIMARY KEY (vid),
    KEY (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS locations;
CREATE TABLE locations (
lid SMALLINT NOT NULL AUTO_INCREMENT,
region VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL,
city VARCHAR(255) NOT NULL,
cemail VARCHAR(255) NOT NULL,
cphone VARCHAR(255) NOT NULL,
need VARCHAR(255) NOT NULL,
season VARCHAR(255) NOT NULL,
days VARCHAR(255) NOT NULL,
opdesc VARCHAR(255) NOT NULL,
startDate VARCHAR(255) NOT NULL,
endDate VARCHAR(255) NOT NULL,
PRIMARY KEY (lid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS seasons;
CREATE TABLE seasons (
sid SMALLINT NOT NULL AUTO_INCREMENT,
lid SMALLINT,
vid SMALLINT,
season VARCHAR(255) NOT NULL,
PRIMARY KEY (sid),
FOREIGN KEY (lid) REFERENCES locations (lid) ON DELETE CASCADE,
FOREIGN KEY (vid) REFERENCES volunteers (vid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS occupations;
CREATE TABLE occupations (
  oid SMALLINT NOT NULL AUTO_INCREMENT,
  lid SMALLINT,
  vid SMALLINT,
  occup VARCHAR(255) NOT NULL,
  PRIMARY KEY (oid),
  FOREIGN KEY (lid) REFERENCES locations (lid) ON DELETE CASCADE,
  FOREIGN KEY (vid) REFERENCES volunteers (vid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS days;
CREATE TABLE days (
  did SMALLINT NOT NULL AUTO_INCREMENT,
  lid SMALLINT,
  vid SMALLINT,
  day VARCHAR(255) NOT NULL,
  PRIMARY KEY (did),
  FOREIGN KEY (lid) REFERENCES locations (lid) ON DELETE CASCADE,
  FOREIGN KEY (vid) REFERENCES volunteers (vid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
SET FOREIGN_KEY_CHECKS=1;